/home/student/cvop_project
dataset:
valid 0.txt test 0.txt
Traceback (most recent call last):
  File "/home/student/cvop_project/model.py", line 258, in <module>
    train_data = VideosDataset2(str(i),all_valid_files[i],all_test_files[i],"train",preload=True,videos_cap=-1)
  File "/home/student/cvop_project/dataset.py", line 258, in __init__
    data,data_k,label=self.get_features(f)
  File "/home/student/cvop_project/dataset.py", line 273, in get_features
    data = np.load(DATA_DIR+"APAS/features/fold"+self.fold_num+"/"+f)
  File "/anaconda/envs/test2/lib/python3.10/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
KeyboardInterrupt